## Get Current User Profile
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZWU5ZGM0Yi1jOWQzLTRkYjctYWI1YS03NjBhZTIxMTA0NzAiLCJlbWFpbCI6Im9jaGllbmdkdW5jYW43ODc4QGdtYWlsLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTAzODM1MCwiZXhwIjoxNzY5Njc4MzUwfQ.GyArOLc60XtaTGTiOCaQtpu_h90UkjCrYd5QgrFaLuY

### Change Password
PATCH http://localhost:3000/users/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZWU5ZGM0Yi1jOWQzLTRkYjctYWI1YS03NjBhZTIxMTA0NzAiLCJlbWFpbCI6Im9jaGllbmdkdW5jYW43ODc4QGdtYWlsLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTAzODM1MCwiZXhwIjoxNzY5Njc4MzUwfQ.GyArOLc60XtaTGTiOCaQtpu_h90UkjCrYd5QgrFaLuY
Content-Type: application/json

{
  "currentPassword": "dante7878",
  "newPassword": "dante1234"
}

### Update Profile
PATCH http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZWU5ZGM0Yi1jOWQzLTRkYjctYWI1YS03NjBhZTIxMTA0NzAiLCJlbWFpbCI6Im9jaGllbmdkdW5jYW43ODc4QGdtYWlsLmNvbSIsInJvbGUiOiJDVVNUT01FUiIsImlhdCI6MTc2MTAzODM1MCwiZXhwIjoxNzY5Njc4MzUwfQ.GyArOLc60XtaTGTiOCaQtpu_h90UkjCrYd5QgrFaLuY
Content-Type: application/json

{
  "name": "Duncan Oyugi",
  "avatarUrl": "http://example.com/new-avatar.jpg"
}
