### REGISTER USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Victor Kiboigo",
  "email": "victorkiboigo0@gmail.com",
  "password": "bilham1234"
}



### VERIFY OTP
POST http://localhost:3000/api/auth/verify-otp
Content-Type: application/json

{
  "email": "victorkiboigo0@gmail.com",
  "otp": "889618"
}


### LOGIN USER
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "ochiengduncan7878@gmail.com",
  "password": "dante1234"
}


### ACCESS PROTECTED ENDPOINT (example)
GET http://localhost:3000/user/profile
Authorization: Bearer {{access_token}}
